<?php/**
 * @var \Dev\Banner\Block\Sample $block
 */?>
<button id="sample" class="float-left submit-button" > <?= $block->getData('title') ?></button>

<script type="text/javascript">
    document.getElementById("sample").onclick = function () {
        location.href = "http://example.com/banner/index/index";
    };
</script>

<style >
    #sample {
        border-radius: 5px;
        width: <?= $block->getData('width') ?>;
        height: <?= $block->getData('height') ?>;
        color: <?= $block->getData('color') ?>;
    }
</style>
